### ISSUE TITLE
Rename operator -> spender.

### ISSUE THREAD

**Issue by jbaylina** [jacquesd/eip777#14]
I like operator, but some native english speaker should decide it.

**Comment by stevenh512** [comment]
I like operator. It does kind of bring to mind an image of an old-timey telephone operator plugging wires into a switchboard, but aside from that, I think it's a good name. As I understand it, the operator is an account that you authorize to perform arbitrary operations with your tokens, so it's more than just a spender or broker. It could be a staking contract, a ring signature mixer, or any number of other things. A generic all-encompassing name like "operator" makes more sense than trying to narrow it down to just a few use cases. Agent, processor or intermediary might also be good alternatives.

**Comment by jacquesd** [comment]
@stevenh512  Yes, operator is (purposefully) very generic. An operator is an account (usually a contract) who can be authorized to manage other accounts (aka send tokens on behalf of the token holder) as well as mint/burn tokens (depending on the specific mint/burn implementation of the token-contract)

I also like the name, it does remind of an old-timey telephone operator with a switchboard. However some people where less convinced with this term. The issue is here to try to find a better name but it is a hard task to find a clear and easily understandable term for such a generic entity.

I think we will probably stick with operator, unless someone comes up with a better name. Any suggestions are welcome!

**Comment by jacquesd** [comment]
I believe at this point we will stick with operator.
If anyone comes up with a better name we will consider it but based on [my above comment](https://github.com/jacquesd/eip777/issues/14#issuecomment-361617902) I think operator is a best term from the list.
