### ISSUE TITLE
Migration error in ReferenceToken constructor

### ISSUE THREAD

**Issue by superduck35** [jacquesd/eip777#68]
## What
Setting up a mock migration in truffle suite to deploy the ReferenceToken (on 0.4.24) results in a Deployment Failed error. 

```
Deploying 'ReferenceToken'
   --------------------------
Error:  *** Deployment Failed ***

"ReferenceToken" hit a require or revert statement somewhere in its constructor. Try:
   * Verifying that your constructor params satisfy all require conditions.
   * Adding reason strings to your require statements.
```

## Why
This is due to the `doMint` function in the constructor which calls the following line
`callRecipient(msg.sender, 0x0, _tokenHolder, _amount, "", _operatorData, true);`

As `preventLocking` is set to true here, only contracts who have implemented `ERC777TokensRecipient` (on 820 client) can receive the tokens.

## Solutions?
1. Remove requirement for token mint recipient to implement interface
2. Pass an extra variable to `doMint` from the constructor to tell it to set `preventLocking == false`
3. Set interface implementation of `ERC777TokensRecipient`

**Comment by 0xjac** [comment]
The behavior you describe here is intentional. Any minting, including in the constructor, must call the `tokensReceived` hook of the recipient if it is a contract.

Solutions 1 & 2 break the standard.

Solution 3 is what you want. If the recipient is the contract itself, in the constructor before the minting you have to register the token contract as a `TokensRecipient` via the ERC1820 registry.

However depending on your use-case you might want to avoid pre-minting tokens. A better alternative could be to mint tokens using signed messages and provide those sign messages to users such that they can mint their own tokens. You could also have a whitelist of addresses each allowed to mint either a fixed amount of tokens or a variable amount of tokens based on how many ether they send, and using a fixed rate.
